include:
  - _includes
  - _pages
  - .doctrees
  - _images
  - _modules
  - _sources
  - _static
keep_files:
  - drugdiscovery/doc

sass:
  style: :compressed

theme: jekyll-theme-primer
  
title: MilaGraphal
description: Project page of MilaGraph group

url: "https://chao1224.github.io"
baseurl: "/DrugTutorial_AAAI2021"
