include:
  - _images
  - _modules
  - _sources
  - _static

sass:
  style: :compressed

theme: jekyll-theme-cayman

description: Website for Drug Discovery Tutorial, AAAI 2021

url: "https://deepgraphlearning.github.io"
baseurl: "/DrugTutorial_AAAI2021"
